apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomerce-shop-dev-deployment
  namespace: ecomerce-shop-dev
  labels: {app: ecomerce-shop-dev}
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector: {matchLabels: {app: ecomerce-shop-dev}}
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
  template:
    metadata:
      labels: {app: ecomerce-shop-dev}
    spec:
      containers:
        - name: ecomerce-shop-dev
          image: trivip002/ecomerce-shop-dev:0f9f84e9f0fb40222d5b7a429f68ba8800684ec0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: ENABLE_HEALTH_CHECK_LOGS
              value: "false"
            - name: NODE_ENV
              value: "production"
            - name: PROD_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecomerce-shop-dev-db
                  key: PROD_DB_USERNAME
            - name: PROD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomerce-shop-dev-db
                  key: PROD_DB_PASSWORD
          resources:
            requests: {cpu: "200m", memory: "512Mi"}
            limits: {memory: "1Gi"}
