apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  namespace: admin-api
  labels: {app: admin-api}
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector: {matchLabels: {app: admin-api}}
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
  template:
    metadata:
      labels: {app: admin-api}
    spec:
      containers:
        - name: admin-api
          image: trivip002/admin-api:c1148be
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests: {cpu: "200m", memory: "512Mi"}
            limits: {memory: "1Gi"}
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          # Nếu app khởi động chậm, startupProbe cho 150s “ân hạn”
          startupProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 30
