apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification
  labels: { app: notification }
spec:
  type: ClusterIP
  selector: { app: notification }
  ports:
    - name: http
      port: 8081
      targetPort: 8081