apiVersion: v1
kind: Service
metadata:
  name: ecommerce-shop-dev-client-service
  namespace: ecommerce-shop-dev-client
spec:
  type: NodePort
  selector:
    app: ecommerce-shop-dev-client
  ports:
    - name: http
      port: 5200
      targetPort: 5200
      nodePort: 30100
